### ISSUE TITLE
autoCloseDelay seem not work

### ISSUE THREAD

**Issue by Giorgiofox** [lprhodes/homebridge-broadlink-rm#131]
Hello,
I'm using latest version (2.5.12) with this configuration, but the Garage when opened not auto close after 10 seconds. What I'm doing wrong?

```
      {
          "name":"Garage",
          "type":"garage-door-opener",
          "autoCloseDelay ":10,
          "data":{
            "open":"b1411c000b130b0c160c16170b170b0c160c160c16170a0c16170b0c150001ea000000000000000000000000",
            "close":"b1211c000b130b0c160c16170b170b0c160c160c16170a0c16170b0c150001ea000000000000000000000000",
            "lock":"",
            "unlock":""
          }
        },
```

**Comment by lprhodes** [comment]
Can you upgrade to 2.5.13 and send through relevant logs please

**Comment by Giorgiofox** [comment]
Hello,
I'm upgraded using:

pi@homebridge:~ $ sudo npm install -g --unsafe-perm homebridge-broadlink-rm 
+ homebridge-broadlink-rm@2.5.13


and still no auto close: I'm using:
    {
          "name":"Garage",
          "type":"garage-door-opener",
          "openCloseDuration":5,
          "autoCloseDelay ":5,
          "data":{
            "open":"b1411c000b130b0c160c16170b170b0c160c160c16170a0c16170b0c150001ea000000000000000000000$
            "close":"b1211c000b130b0c160c16170b170b0c160c160c16170a0c16170b0c150001ea00000000000000000000$
            "lock":"",
            "unlock":""
          }
        },

**Comment by Giorgiofox** [comment]
Sorry, this is the log:
[6/30/2017, 3:18:37 PM] [Broadlink RM] Garage setTargetDoorState: 1
[6/30/2017, 3:18:37 PM] [Broadlink RM] Garage sendHex (192.168.0.65; 34:ea:34:f4:53:15)
[6/30/2017, 3:18:42 PM] [Broadlink RM] Garage setCurrentDoorState: closed
[6/30/2017, 3:18:42 PM] [Broadlink RM] Garage setCurrentDoorState: 1
[6/30/2017, 3:18:43 PM] [Broadlink RM] Garage setTargetDoorState: 0
[6/30/2017, 3:18:43 PM] [Broadlink RM] Garage sendHex (192.168.0.65; 34:ea:34:f4:53:15)
[6/30/2017, 3:18:48 PM] [Broadlink RM] Garage setCurrentDoorState: open
[6/30/2017, 3:18:48 PM] [Broadlink RM] Garage setCurrentDoorState: 0

**Comment by nigg** [comment]
some issue here. auto close does not work

**Comment by lprhodes** [comment]
Fixed in 2.5.14

**Comment by Giorgiofox** [comment]
pi@homebridge:~ $ sudo npm install -g --unsafe-perm homebridge-broadlink-rm
+ homebridge-broadlink-rm@2.5.14
updated 1 package in 3.786s


Still not working for me :-|

Maybe I'm using wrong something?

**Comment by lprhodes** [comment]
New logs please (I updated some of the logging)

**Comment by Giorgiofox** [comment]
After updating, still not work: I've tried to  to update both:

`sudo npm install -g --unsafe-perm homebridge-broadlink-rm
`
and

`sudo npm update -g homebridge-broadlink-rm
`
In log I've only this:

**[7/9/2017, 6:46:52 AM] [Broadlink RM] Garage setTargetDoorState: 1
[7/9/2017, 6:46:52 AM] [Broadlink RM] Garage sendHex (192.168.0.65; 34:ea:34:f4:53:15)
[7/9/2017, 6:46:57 AM] [Broadlink RM] Garage setCurrentDoorState: closed
[7/9/2017, 6:46:57 AM] [Broadlink RM] Garage setCurrentDoorState: 1
[7/9/2017, 6:46:59 AM] [Broadlink RM] Garage setTargetDoorState: 0
[7/9/2017, 6:46:59 AM] [Broadlink RM] Garage sendHex (192.168.0.65; 34:ea:34:f4:53:15)
[7/9/2017, 6:47:04 AM] [Broadlink RM] Garage setCurrentDoorState: open
[7/9/2017, 6:47:04 AM] [Broadlink RM] Garage setCurrentDoorState: 0**

**Comment by Giorgiofox** [comment]
Maybe the problem is that after opening the CurrestDoorState remain 0 ?

**Comment by lprhodes** [comment]
You have a space at the end of `autoCloseDelay` in your config

"autoCloseDelay ":5,

**Comment by Giorgiofox** [comment]
No, I'm using Sublime Text with rsub:
No space after autoCloseDelay
<img width="498" alt="screenshot 2017-07-09 17 23 14" src="https://user-images.githubusercontent.com/1769743/27995271-5257051a-64cb-11e7-8f8f-d5beb86b8a99.png">
