### ISSUE TITLE
TypeError: Assignment to constant variable at FanAccessory.getServices 

### ISSUE THREAD

**Issue by DJay-X** [lprhodes/homebridge-broadlink-rm#239]
After updating to homebridge-broadlink-rm@2.6.2
homebridge crashed with the enclosed error. 

Part of my config.json is this. Any idea? I didn't change anything to the previous version of the plugin.

```
{
                                 "name": "GreenFan",
                                 "type": "fan",
                                 "hideSwingMode":true,
                                 "hideV2Fan":true,
                                 "data": {
                                 "on":"26004800000128921411141114351510141113111511133614111435153514351535143613361436143613111510141114351510141114111411143514361436131115351435153415000d05",
                                 "off":"26004800000128921411141114351510141113111511133614111435153514351535143613361436143613111510141114351510141114111411143514361436131115351435153415000d05",
                                 "fanSpeed10": "26004800000127931212141212371312141112121511123614121237133613371337133613371336141212371312131212371312141113121435141113361436131213371237133615000d05",
                                 "fanSpeed20": "26004800000127931212141212371312141112121511123614121237133613371337133613371336141212371312131212371312141113121435141113361436131213371237133615000d05",
                                 "fanSpeed30": "26004800000127931212141212371312141112121511123614121237133613371337133613371336141212371312131212371312141113121435141113361436131213371237133615000d05",
                                 "fanSpeed40": "26004800000127931212141212371312141112121511123614121237133613371337133613371336141212371312131212371312141113121435141113361436131213371237133615000d05",
                                 "fanSpeed50": "26004800000127931212141212371312141112121511123614121237133613371337133613371336141212371312131212371312141113121435141113361436131213371237133615000d05",
                                 "fanSpeed60": "26004800000129911411131115351411131214111212133713111436143614351535143513371337123713371312141112371312141014121411121215351237131213361535153413000d05",
                                 "fanSpeed70": "26004800000129911411131115351411131214111212133713111436143614351535143513371337123713371312141112371312141014121411121215351237131213361535153413000d05",
                                 "fanSpeed80": "26004800000129911411131115351411131214111212133713111436143614351535143513371337123713371312141112371312141014121411121215351237131213361535153413000d05",
                                 "fanSpeed90": "26004800000129911411131115351411131214111212133713111436143614351535143513371337123713371312141112371312141014121411121215351237131213361535153413000d05",
                                 "fanSpeed100": "26004800000129911411131115351411131214111212133713111436143614351535143513371337123713371312141112371312141014121411121215351237131213361535153413000d05"
                                 }
                                 }]},
```

```
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing BroadlinkRM platform...
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] The "switch-multi" type requires the config value for "data" to be an array of hex codes.
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] The "switch-multi" type requires the config value for "data" to be an array of hex codes.
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing platform accessory 'Learn'...
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing platform accessory 'Scan Frequency'...
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing platform accessory 'Lautstärke hoch'...
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing platform accessory 'Lautstärke runter'...
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing platform accessory 'Sendungsinfo'...
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing platform accessory 'Zurück zum laufenden Programm'...
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing platform accessory 'Sendung aufzeichnen'...
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing platform accessory 'Lautstärke stumm'...
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing platform accessory 'Fersehguide'...
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing platform accessory '3D'...
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing platform accessory 'Display'...
Feb 09 11:57:53 raspberrypi homebridge[7665]: [2018-2-9 11:57:53] [Broadlink RM] Initializing platform accessory 'GreenFan'...
Feb 09 11:57:53 raspberrypi homebridge[7665]: /usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/fan.js:46
Feb 09 11:57:53 raspberrypi homebridge[7665]: if (showV2Fan !== false) showV2Fan = true
Feb 09 11:57:53 raspberrypi homebridge[7665]: ^
Feb 09 11:57:53 raspberrypi homebridge[7665]: TypeError: Assignment to constant variable.
Feb 09 11:57:53 raspberrypi homebridge[7665]: at FanAccessory.getServices (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/fan.js:46:40)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:388:36)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:374:32)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
Feb 09 11:57:53 raspberrypi homebridge[7665]: at BroadlinkRMPlatform.accessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:40:5)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:364:20)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:308:16)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at Module._compile (module.js:643:30)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at Object.Module._extensions..js (module.js:654:10)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at Module.load (module.js:556:32)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at tryModuleLoad (module.js:499:12)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at Function.Module._load (module.js:491:3)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at Function.Module.runMain (module.js:684:10)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at startup (bootstrap_node.js:187:16)
Feb 09 11:57:53 raspberrypi homebridge[7665]: at bootstrap_node.js:608:3
Feb 09 11:57:53 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Feb 09 11:57:53 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
Feb 09 11:58:01 raspberrypi systemd[1]: Stopping Node.js HomeKit Server...
Feb 09 11:58:01 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
```

**Comment by lprhodes** [comment]
Sorry - fixed in 2.6.3

**Comment by DJay-X** [comment]
Thanks. And first, I appreciate your work and sharing it with us. This is not for granted. Thanks for investing your time. 👍🏻

When I reinstall I still get 2.6.2 and also with sudo npm install -g homebridge-broadlink-rm@2.6.3
