### ISSUE TITLE
ReferenceError starting plugin 

### ISSUE THREAD

**Issue by FrothyDog** [lprhodes/homebridge-broadlink-rm#245]
My homebridge plugin has been working fine and today it suddenly started crashing on startup. I am seeing an error in the fan.js file (line 48). See the attached screenshot from the terminal:
![reference_error](https://user-images.githubusercontent.com/35815728/36079918-67cca194-0f3d-11e8-891d-74b41ee0ac30.jpg)

**Comment by lprhodes** [comment]
Fixed in the latest release

**Comment by FrothyDog** [comment]
I am running from an install.sh file. Shouldn't "npm install -gs homebridge-broadlink-rm" get the latest releases? I am still seeing this error.

**Comment by lprhodes** [comment]
It should result in

"+ homebridge-broadlink-rm@2.6.5
updated 1 package in 1.769s"
