### ISSUE TITLE
minTemperature cannot be above 10C

### ISSUE THREAD

**Issue by lits101** [lprhodes/homebridge-broadlink-rm#310]
It seems I can't set the "minTemperature" variable on an "air-conditioner" to anything above 10 degrees celsius.

Attempting to do so causes homebridge to crash on start. 

My A/C unit only goes as low as 16 - so having this hard-coded limit seems a bit silly.

**Comment by j796160836** [comment]
Hi @lits101,
I think you haven't set `pseudoDeviceTemperature` in your config. So it default is `0 °C` and you set `minTemperature` to `10 °C` and cause the error.

Here is the config what I use. Only `heater to 27°C`, `cooler to 26°C` and `off`, three modes, FYI.

```
{
  "name": "air-conditioner",
  "type": "air-conditioner",
  "defaultHeatTemperature": 27,
  "defaultCoolTemperature": 26,
  "pseudoDeviceTemperature": 26,
  "data": {
    "off": "2600b602...",
    "temperature27": {
      "pseudo-mode": "heat",
      "data": "2600b602723..."
    },
    "temperature26": {
      "pseudo-mode": "cool",
      "data": "2600b6027036..."
    }
  }
}
```

**Comment by lits101** [comment]
Nope - I've got "pseudoDeviceTemperature" set to 25.

Setting 

`                                {
                                        "name":"Air Conditioner",
                                        "type":"air-conditioner",
                                        "defaultCoolTemperature": 24,
                                        "defaultHeatTemperature": 25,
                                        "pseudoDeviceTemperature": 25,
                                        "replaceAutoMode":"cool",
                                        "minTemperature": 10,
                                        "data":{
                                                "on":"26004c026f360f290e290e0e0e0e0d0f0d290e0e0e0e0d290f290e0e0e280f0e0d0f0d290e290e0f0d290$
                                                "off":"26004c02713510271027100b110a110b1127100b110b10281027100b1028100b100b11271027100b1127$
                                                "temperature30":{
                                                        "pseudo-mode":"heat",
                                                        "data":"26004c02703610271027100c100b100c10280f0c100b10281027100b1028100b100c10280f2$
                                                        },
                                                "temperature29":{
                                                        "pseudo-mode":"heat",
                                                        "data":"26004c02713510271027100b110b110a1127100b110b11271027100b1127100b110a1127102$
                                                        },
   `

**Comment by cubilon** [comment]
+1.
could be useful having a start temp from the one you can manage with the A/C, in my case it's 16.
btw, I think this plugin behave is caused from a HomeKit bug, but I'm not sure about that.

**Comment by lprhodes** [comment]
It has to be <= 10 otherwise the Home app starts having issues sorry 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mu2004** [comment]
It's been a while, and perhaps Home app has sorted out the bug in the newer iOS. Is it possible to try again to have the minTemperature to be 20, especially for a cooling only AC? So the slider doesn't travel a long way to the very top for the >24 temperature that people actually use for cooling.

**Comment by eden881** [comment]
I need this too - my AC only goes as low as 16C.
Any chance that this bug has been solved?

**Comment by unickq** [comment]
> It has to be <= 10 otherwise the Home app starts having issues sorry
> 
> Sent with [GitHawk](http://githawk.com)

@lprhodes
any updates on that? Does HomeApp still have this issue?

**Comment by jeylites** [comment]
I'm having the same issue as well, my AC  - Low is 16C & High is 30C. No heater mode only cool. Is there a work around to get the correct temp to show up on Homekit app?

I've been experimenting setting the low to -9 and max to 0, as copied below. Would appreciate if someone could give a second opinion on this method to trick Homekit into showing the right temp.

 ```
"platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "accessories": [
                {
                    "name": "Air Conditioner Advanced",
                    "type": "air-conditioner",
                    "tempUnit": "Celsius",
                    "allowResend": true,
                    "preventResendHex": true,
                    "ignoreTemperatureWhenOff": true,
                    "replaceAutoMode": "cool",
                    "autoSwitch": "A/C Auto Switch",
                    "hideWelcomeMessage": true,
                    "minTemperature": -9,
                    "maxTemperature": 0,
                    "pseudoDeviceTemperature": 10,
                    "temperatureUpdateFrequency": 20,
                    "data": {
                        "off": "0000 0058 0000 0043 00DD 007C 0012 0012 0012 002D 0012 002D 0012 0012 0012 002D 0012 0012 0012 0012 0012 0012 0012 0012 0012 002D 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 002D 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 002D 0012 002D 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 0012 002D 0012 0012 0012 0012 0012 002D 0012 0012 0012 0012 0012 002D 0012 002D 0012 0012 0012 002D 0012 0012 0012 03B3 00DD 0298",
                        "temperature16": {
                            "pseudo-mode": "cool",
                            "data": "0000 007A 0000 0043 00A0 005A 000D 000D 000D 0021 000D 0021 000D 000D 000D 0021 000D 000D 000D 000D 000D 000D 000D 000D 000D 0021 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 0021 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 0021 000D 0021 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 000D 0021 000D 0021 000D 000D 000D 0021 000D 000D 000D 000D 000D 000D 000D 0021 000D 000D 000D 000D 000D 000D 000D 000D 000D 0021 000D 000D 000D 000D 000D 02AE 00A0 01E1"
                        },
                        "temperature17": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature18": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature19": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature20": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature21": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature22": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature23": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature24": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature25": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature26": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature27": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature28": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature29": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        },
                        "temperature30": {
                            "pseudo-mode": "cool",
                            "data": "HEX CODE"
                        }
```
