### ISSUE TITLE
error loading plugin, Cannot find module 'hap-nodejs' with Homebridge V1.0 and up - fixed in  Defensor7 fork

### ISSUE THREAD

**Issue by gargamelonly** [lprhodes/homebridge-broadlink-rm#614]
```
[4/27/2020, 12:15:38 PM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[4/27/2020, 12:15:39 PM] Error: Cannot find module 'hap-nodejs'
Require stack:
- /homebridge/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/accessory.js
- /homebridge/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/index.js
- /homebridge/node_modules/homebridge-broadlink-rm/platform.js
- /homebridge/node_modules/homebridge-broadlink-rm/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/index.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/src/accessory.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
[4/27/2020, 12:15:39 PM] ====================
```

**Comment by Silentbob101** [comment]
I am having the same issue

**Comment by bushshrub** [comment]
What version of homebridge are you running?

**Comment by gargamelonly** [comment]
1.0.1

**Comment by bushshrub** [comment]
If I'm correct, this plugin hasn't been updated to Homebridge v1. Try rolling homebridge back to the previous version.

**Comment by dewoert** [comment]
Problem is since v3.6.20 (or so), and also in older HomeBridge versions.
I'm running HomeBridge 1.0.4 without problems, but with older version of homebridge-broadlink-rm (**3.6.18**)

`npm remove homebridge-broadlink-rm`
`npm install -save homebridge-broadlink-rm@v3.6.18`

Tries serveral solutions, none seem to work.
Plugin needs te be reviewed and updated.

**Comment by gargamelonly** [comment]
It feels like this plugin has been abandoned by the creator.

**Comment by bencharlesrhys** [comment]
> Problem is since v3.6.20 (or so), and also in older HomeBridge versions.
> I'm running HomeBridge 1.0.4 without problems, but with older version of homebridge-broadlink-rm (**3.6.18**)
> 
> `npm remove homebridge-broadlink-rm`
> `npm install -save homebridge-broadlink-rm@v3.6.18`
> 
> Tries serveral solutions, none seem to work.
> Plugin needs te be reviewed and updated.

Thank you this fixed the issue for me.

**Comment by gargamelonly** [comment]
notice when installing the plugin some warnings:
`make: Entering directory '/homebridge/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/build'
  CXX(target) Release/obj.target/raw/src/raw.o
In file included from ../src/raw.h:23,
                 from ../src/raw.cc:6:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2294:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
 2294 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from ../src/raw.h:21,
                 from ../src/raw.cc:6:
../src/raw.cc: At global scope:
/root/.cache/node-gyp/12.16.2/include/node/node.h:608:43: warning: cast between incompatible function types from 'void (*)(v8::Local<v8::Object>)' to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
  608 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/root/.cache/node-gyp/12.16.2/include/node/node.h:642:3: note: in expansion of macro 'NODE_MODULE_X'
  642 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/raw.cc:55:1: note: in expansion of macro 'NODE_MODULE'
   55 | NODE_MODULE(raw, InitAll)
      | ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/raw.node
  COPY Release/raw.node
make: Leaving directory '/homebridge/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/build'
+ homebridge-broadlink-rm@3.6.18`

**Comment by gargamelonly** [comment]
I installed  **Defensor7/homebridge-broadlink-rm**  plugin which is a fork of this one and it is working also with RM3mini. He fixed it in his fork.

**Comment by bencharlesrhys** [comment]
It doesn't look like it's in npm. How can I install the forked version?

**Comment by Ant1q** [comment]
> It doesn't look like it's in npm. How can I install the forked version?

it looks like subject fork https://www.npmjs.com/package/homebridge-broadlink-rm4

**Comment by ffaamm** [comment]
I too just runned into this problem, it seems solved by manually installing `hap-nodejs`.
`npm install -g hap-nodejs`

Some references:
`node -v v12.16.3`
`npm -v 6.14.5`
`homebridge v1.0.4`
`homebridge-config-ui-x v4.18.0`

**Comment by SSutherland94** [comment]
> I installed **Defensor7/homebridge-broadlink-rm** plugin which is a fork of this one and it is working also with RM3mini. He fixed it in his fork.

I'm still having trouble with the Defensor fork. I honestly have no idea what I'm doing wrong. The plugin isn't detecting my device, and when I input the IP and MAC manually, I still get hit with "Device not found". I have an RM Mini3, and I think the PID, according to the Broadlink app, is 3727. I also tried the homebridge-broadlink-rm-tv plugin to no avail. And help would be greatly appreciated. I have everything else running buttery smooth in Homebridge except this.

**Comment by bencharlesrhys** [comment]
> I too just runned into this problem, it seems solved by manually installing `hap-nodejs`.
> `npm install -g hap-nodejs`
> 
> Some references:
> `node -v v12.16.3`
> `npm -v 6.14.5`
> `homebridge v1.0.4`
> `homebridge-config-ui-x v4.18.0`

I tried your suggestion but didn't work. Then I removed the global and it worked!

`npm install hap-nodejs`

Using the oznu DSM Synology container.
